// ============================================================
// 《李豆沙的次元冲刺·后编》剧情 —— Kimo熊 存档点版
// 核心设定：存档点熊猫 = Kimo熊留下的"存档锚点"。
// Kimo熊不是幕后黑手，是这个 LowPoly 世界的引路人和守护者：
// 不能改变世界规则，只能在规则允许的地方放锚点，
// 把掉落的两人接回安全位置。终章于裂缝旁的最后一个锚点现身。
// 主题：Kimo熊能把豆沙的失败回档，但不能替她走出这个世界。
// 真正陪豆沙跳进未知的，是室友姐。
// ============================================================
import { YuriEvent } from '../types';

export const EVENTS3D: Record<string, YuriEvent> = {
  // ---------- 序章：第二层世界 ----------
  'event_prologue': {
    id: 'event_prologue',
    requiredPageId: '',
    startNodeId: 'p1',
    nodes: {
      'p1': { id: 'p1', speakerName: '李豆沙',
        text: '……到了？小室？我们是不是出来了？',
        choices: [{ id: 'c', text: '（环顾四周）', nextNodeId: 'p2' }] },
      'p2': { id: 'p2', speakerName: '室友姐',
        text: '先别高兴太早。你低头看看自己的手。',
        choices: [{ id: 'c', text: '（低头）', nextNodeId: 'p3' }] },
      'p3': { id: 'p3', speakerName: '李豆沙',
        text: '……啊啊啊啊我的手怎么变成方块了？！',
        choices: [{ id: 'c', text: '（惊恐地翻看手心手背）', nextNodeId: 'p4' }] },
      'p4': { id: 'p4', speakerName: '室友姐',
        text: '不只是手。地面、天空、远处的树，全都变成了多边形。',
        choices: [{ id: 'c', text: '（抬头看天）', nextNodeId: 'p5' }] },
      'p5': { id: 'p5', speakerName: '李豆沙',
        text: '所以……我们不是回到现实了？那刚才那扇门到底是什么？出口？还是另一个入口？',
        choices: [{ id: 'c', text: '（看向小室）', nextNodeId: 'p6' }] },
      'p6': { id: 'p6', speakerName: '室友姐',
        text: '至少可以确定一件事。我们逃出了漫画世界——但没有逃出"世界"。',
        choices: [{ id: 'c', text: '……这句话一点都不让人安心。', nextNodeId: 'p7' }] },
      'p7': { id: 'p7', speakerName: '李豆沙',
        text: '（走了几步，突然扶住额头）等一下……这个视角……这个深度……我好像有点晕3D……',
        choices: [{ id: 'c', text: '（蹲下缓一缓）', nextNodeId: 'p8' }] },
      'p8': { id: 'p8', speakerName: '室友姐',
        text: '我猜到了。（掏出一把薄荷糖）拿着，先含一颗。你要是一路晕到出口，我还得拖着一只方块熊猫跑完全程。',
        choices: [{ id: 'c', text: '你怎么连这种东西都准备了啊……', nextNodeId: 'p9' }] },
      'p9': { id: 'p9', speakerName: '室友姐',
        text: '因为我室友是个在什么世界都会晕的笨蛋。',
        choices: [{ id: 'c', text: '我才不是笨蛋。', nextNodeId: 'p10' }] },
      'p10': { id: 'p10', speakerName: '室友姐',
        text: '嗯，方块笨蛋。（两人往前走，路边蹲着一个白白的小家伙）',
        choices: [{ id: 'c', text: '（凑近看）', nextNodeId: 'p11' }] },
      'p11': { id: 'p11', speakerName: '李豆沙',
        text: '这是……熊猫？为什么存档点会长成熊猫？',
        choices: [{ id: 'c', text: '（戳了戳它的脸颊）', nextNodeId: 'p12' }] },
      'p12': { id: 'p12', speakerName: '室友姐',
        text: '看起来像存档点。也许这个世界的审美还不错。',
        choices: [{ id: 'c', text: '你是在说它可爱，还是在说我可爱？', nextNodeId: 'p13' }] },
      'p13': { id: 'p13', speakerName: '室友姐',
        text: '我说存档点。',
        choices: [{ id: 'c', text: '……哦。', nextNodeId: 'p14' }] },
      'p14': { id: 'p14', speakerName: '室友姐',
        text: '走吧。先记住这里。万一你又摔下去，至少知道会从哪儿醒来。',
        choices: [{ id: 'c', text: '出发！', nextNodeId: null }] },
    },
  },

  // ---------- 第1关后：第二层 · 第一张纸条 ----------
  'event3d_level1': {
    id: 'event3d_level1',
    requiredPageId: 'page3d_ch1',
    startNodeId: 's1',
    nodes: {
      's1': { id: 's1', speakerName: '李豆沙',
        text: '小室，这个不是漫画页。',
        choices: [{ id: 'c', text: '（把捡到的纸递过去）', nextNodeId: 's2' }] },
      's2': { id: 's2', speakerName: '室友姐',
        text: '嗯。没有分镜，也没有对白框。',
        choices: [{ id: 'c', text: '上面画的是我们刚才走过的路？', nextNodeId: 's3' }] },
      's3': { id: 's3', speakerName: '室友姐',
        text: '不完全是。你看这里，这座桥我们刚才走过，但纸上只记录了一半。',
        choices: [{ id: 'c', text: '所以这个世界也在被画？', nextNodeId: 's4' }] },
      's4': { id: 's4', speakerName: '室友姐',
        text: '不一定是画。更像是在生成——我们往前走，它才把后面的路补出来。像是这个世界只在我们看见的地方存在。',
        choices: [{ id: 'c', text: '……听起来更可怕了。（翻到纸的背面）', nextNodeId: 's5' }] },
      's5': { id: 's5', speakerName: '李豆沙',
        text: '（背面有一行字：欢迎来到第二层。——Kimo熊）……第二层？',
        choices: [{ id: 'c', text: '（把纸条举给小室看）', nextNodeId: 's6' }],
        backgroundStyle: 'MANGA' },
      's6': { id: 's6', speakerName: '室友姐',
        text: '也就是说，漫画世界是第一层。',
        choices: [{ id: 'c', text: '那现实是第几层？这个 Kimo 熊又是谁？', nextNodeId: 's7' }] },
      's7': { id: 's7', speakerName: '室友姐',
        text: '不知道。但至少，它知道我们从哪里来。',
        choices: [{ id: 'c', text: '它在帮我们？', nextNodeId: 's8' }] },
      's8': { id: 's8', speakerName: '室友姐',
        text: '也可能是在观察我们。',
        choices: [{ id: 'c', text: '你能不能说点安心的话？', nextNodeId: 's9' }] },
      's9': { id: 's9', speakerName: '室友姐',
        text: '可以。——不管第几层，你先别松手。',
        choices: [
          { id: 'a', text: '我才没有怕到要牵手！', nextNodeId: 'ra' },
          { id: 'b', text: '那你牵紧一点。', affectionDelta: { charId: 'novus', amount: 15 }, nextNodeId: 'rb' },
          { id: 'cS', text: '【直球】第几层都没关系，只要你还在我旁边。', affectionDelta: { charId: 'novus', amount: 50 }, nextNodeId: 'rc', requiresClear: true },
        ] },
      'ra': { id: 'ra', speakerName: '室友姐',
        text: '嗯。那就当是我要牵的。（不由分说握住）',
        choices: [{ id: 'c', text: '（也没有甩开就是了……）', nextNodeId: 'end' }] },
      'rb': { id: 'rb', speakerName: '室友姐',
        text: '（收紧手指）……嗯。',
        choices: [{ id: 'c', text: '（掌心很暖。）', nextNodeId: 'end' }] },
      'rc': { id: 'rc', speakerName: '室友姐',
        text: '（愣了一下，别开视线）……笨蛋。走了。',
        choices: [{ id: 'c', text: '（她的耳朵红了。记下来了。）', nextNodeId: 'end' }] },
      'end': { id: 'end', speakerName: '李豆沙',
        text: '（第一张纸条，收好了。第二层的路，还很长。……纸条的边角上，还印着两个小小的字母。）',
        choices: [{ id: 'c', text: '……', nextNodeId: null }] },
    },
  },

  // ---------- 第2关后：不是世界在复活你 · 第二张纸条 ----------
  'event3d_level2': {
    id: 'event3d_level2',
    requiredPageId: 'page3d_ch2',
    startNodeId: 's1',
    nodes: {
      's1': { id: 's1', speakerName: '李豆沙',
        text: '（刚从熊猫存档点旁边醒来）刚才我掉下去了。掉了很久。然后我又回来了。',
        choices: [{ id: 'c', text: '（看向小室）', nextNodeId: 's2' }] },
      's2': { id: 's2', speakerName: '室友姐',
        text: '我看见了。',
        choices: [{ id: 'c', text: '你就不能表现得震惊一点吗？', nextNodeId: 's3' }] },
      's3': { id: 's3', speakerName: '室友姐',
        text: '你已经替我们两个震惊完了。',
        choices: [{ id: 'c', text: '小室！！', nextNodeId: 's4' }] },
      's4': { id: 's4', speakerName: '室友姐',
        text: '不过，这件事确实奇怪。你不是随机回来的——每次掉下去，你都会从最近的熊猫存档点旁边醒来。',
        choices: [{ id: 'c', text: '所以它不是装饰？', nextNodeId: 's5' }] },
      's5': { id: 's5', speakerName: '室友姐',
        text: '不是。',
        choices: [{ id: 'c', text: '那它到底是在存档，还是在救我？', nextNodeId: 's6' }] },
      's6': { id: 's6', speakerName: '室友姐',
        text: '也许两者都是。至少，它把你的坐标回档到了安全的位置。',
        choices: [{ id: 'c', text: '那这个熊猫就是 Kimo 熊？', nextNodeId: 's7' }] },
      's7': { id: 's7', speakerName: '室友姐',
        text: '还不能确定。但名字对得上。',
        choices: [{ id: 'c', text: '（在熊猫存档点下面摸到了第二张纸条）', nextNodeId: 's8' }] },
      's8': { id: 's8', speakerName: '李豆沙',
        text: '（纸条：不要相信眼前所有的出口。但如果掉下去，我会在这里等你。——Kimo熊）……它真的在等我们。',
        choices: [{ id: 'c', text: '（攥紧了纸条）', nextNodeId: 's9' }],
        backgroundStyle: 'MANGA' },
      's9': { id: 's9', speakerName: '室友姐',
        text: '嗯。它是不是这个世界的人，不知道。但至少——它不是想把我们困在这里的人。',
        choices: [
          { id: 'a', text: '那我以后掉下去之前先跟它打个招呼。', nextNodeId: 'ra' },
          { id: 'b', text: '我还以为每次都是你把我捡回来的。', affectionDelta: { charId: 'novus', amount: 15 }, nextNodeId: 'rb' },
          { id: 'cS', text: '【直球】如果我总会回到 Kimo 熊这里，那你也一定要在这里等我。', affectionDelta: { charId: 'novus', amount: 50 }, nextNodeId: 'rc', requiresClear: true },
        ] },
      'ra': { id: 'ra', speakerName: '室友姐',
        text: '打招呼之前，先练练别掉下去。',
        choices: [{ id: 'c', text: '呜……努力。', nextNodeId: 'end' }] },
      'rb': { id: 'rb', speakerName: '室友姐',
        text: '（顿了一下）……它负责接。我负责等你睁开眼的时候，第一个被看到。',
        choices: [{ id: 'c', text: '（心跳漏了一拍。）', nextNodeId: 'end' }] },
      'rc': { id: 'rc', speakerName: '室友姐',
        text: '（很轻地叹了口气，蹲下来和你平视）说什么呢。你醒来的每一次，我哪次不在？',
        choices: [{ id: 'c', text: '（……好像，确实每次都在。）', nextNodeId: 'end' }] },
      'end': { id: 'end', speakerName: '李豆沙',
        text: '（第二张纸条。原来每一次复活，都是有谁在把我的数据读档回来。）',
        choices: [{ id: 'c', text: '……', nextNodeId: null }] },
    },
  },

  // ---------- 第3关后：线框层与会重排的世界 · 第三张纸条 ----------
  'event3d_level3': {
    id: 'event3d_level3',
    requiredPageId: 'page3d_ch3',
    startNodeId: 's1',
    nodes: {
      's1': { id: 's1', speakerName: '李豆沙',
        text: '小室，我刚才切到黑白层的时候看清楚了。那不是漫画层。',
        choices: [{ id: 'c', text: '（比划着刚才看到的东西）', nextNodeId: 's2' }] },
      's2': { id: 's2', speakerName: '室友姐',
        text: '我也注意到了。没有分镜，没有网点，也没有对白框。',
        choices: [{ id: 'c', text: '全都是线。', nextNodeId: 's3' }] },
      's3': { id: 's3', speakerName: '室友姐',
        text: '更像建模软件里的线框视图。',
        choices: [{ id: 'c', text: '所以这个世界不是被画出来的。', nextNodeId: 's4' }] },
      's4': { id: 's4', speakerName: '室友姐',
        text: '是被搭出来的。',
        choices: [{ id: 'c', text: '之前的漫画世界是一本漫画，这里是一个模型？我们到底掉进了什么东西里啊……', nextNodeId: 's5' }] },
      's5': { id: 's5', speakerName: '李豆沙',
        text: '（远处的平台突然咔哒一声，重新排列了）等等！那条路刚才不是那样的！',
        choices: [{ id: 'c', text: '（拽住小室的袖子）', nextNodeId: 's6' }],
        backgroundStyle: 'MANGA' },
      's6': { id: 's6', speakerName: '室友姐',
        text: '它改了。',
        choices: [{ id: 'c', text: '谁改的？！', nextNodeId: 's7' }] },
      's7': { id: 's7', speakerName: '室友姐',
        text: '不一定是"谁"。也许这个世界自己会修正错误。',
        choices: [{ id: 'c', text: '错误？', nextNodeId: 's8' }] },
      's8': { id: 's8', speakerName: '室友姐',
        text: '比如——我们走到了不该知道的地方。',
        choices: [{ id: 'c', text: '（在熊猫存档点旁边发现了第三张纸条）', nextNodeId: 's9' }] },
      's9': { id: 's9', speakerName: '李豆沙',
        text: '（纸条：我不能改路。也不能阻止世界重排。我只能在你们坠落的时候，把你们的数据回滚到还能继续走的位置。——Kimo熊）',
        choices: [{ id: 'c', text: '所以之前每次复活，都是它……', nextNodeId: 's10' }],
        backgroundStyle: 'MANGA' },
      's10': { id: 's10', speakerName: '室友姐',
        text: '嗯。不是系统，也不是世界的温柔。是有人一直守着你的存档，在你坠落的瞬间把你回滚回来。',
        choices: [{ id: 'c', text: '那它自己呢？', nextNodeId: 's11' }] },
      's11': { id: 's11', speakerName: '室友姐',
        text: '它大概一直留在原地。',
        choices: [{ id: 'c', text: '等下一个掉下来的人？', nextNodeId: 's12' }] },
      's12': { id: 's12', speakerName: '室友姐',
        text: '等你。',
        choices: [
          { id: 'a', text: '听起来好寂寞。', nextNodeId: 'ra' },
          { id: 'b', text: '如果它也被困着，那我们出去以后能不能带它一起走？', affectionDelta: { charId: 'novus', amount: 15 }, nextNodeId: 'rb' },
          { id: 'cS', text: '【直球】那你也要看着我。不是控制，是看着我走出去。', affectionDelta: { charId: 'novus', amount: 50 }, nextNodeId: 'rc', requiresClear: true },
        ] },
      'ra': { id: 'ra', speakerName: '室友姐',
        text: '嗯。所以路过它的时候，记得摸摸头。',
        choices: [{ id: 'c', text: '（下次一定！）', nextNodeId: 'end' }] },
      'rb': { id: 'rb', speakerName: '室友姐',
        text: '（看了你两秒，眼神软下来）……你这个人啊。好。到时候问问它愿不愿意。',
        choices: [{ id: 'c', text: '（一言为定！）', nextNodeId: 'end' }] },
      'rc': { id: 'rc', speakerName: '室友姐',
        text: '（黑白的线框世界里，只有她的声音是有温度的）……一直都在看。从第一层就在看。',
        choices: [{ id: 'c', text: '（心跳声在线框层里格外清楚。）', nextNodeId: 'end' }] },
      'end': { id: 'end', speakerName: '李豆沙',
        text: '(第三张纸条。它不能改写规则——但它一直在规则的缝隙里，替我保管着每一份存档。）',
        choices: [{ id: 'c', text: '……', nextNodeId: null }] },
    },
  },

  // ---------- 第4关后：世界边缘的裂缝 · 第四张纸条 ----------
  'event3d_level4': {
    id: 'event3d_level4',
    requiredPageId: 'page3d_ch4',
    startNodeId: 's1',
    nodes: {
      's1': { id: 's1', speakerName: '室友姐',
        text: '（云端平台。远处的天空像模型面片没接好，露出一道细长的亮缝）豆沙，看那边。',
        choices: [{ id: 'c', text: '那条亮线？', nextNodeId: 's2' }] },
      's2': { id: 's2', speakerName: '室友姐',
        text: '嗯。天空在那里没有接上。',
        choices: [{ id: 'c', text: '像模型穿模了。', nextNodeId: 's3' }] },
      's3': { id: 's3', speakerName: '室友姐',
        text: '对。也像世界的边界漏了一条缝。',
        choices: [{ id: 'c', text: '那会不会是出口？', nextNodeId: 's4' }] },
      's4': { id: 's4', speakerName: '室友姐',
        text: '有可能。',
        choices: [{ id: 'c', text: '可是 Kimo 熊说，不要相信所有出口。', nextNodeId: 's5' }] },
      's5': { id: 's5', speakerName: '室友姐',
        text: '所以问题不是"它是不是出口"。是谁，让我们看到它。',
        choices: [{ id: 'c', text: '（这时，附近的熊猫存档点亮了一下）刚才……它是不是亮了？', nextNodeId: 's6' }],
        backgroundStyle: 'MANGA' },
      's6': { id: 's6', speakerName: '室友姐',
        text: '嗯。像是在回应。',
        choices: [{ id: 'c', text: '（从熊猫存档点下方摸出第四张纸条）', nextNodeId: 's7' }] },
      's7': { id: 's7', speakerName: '李豆沙',
        text: '（纸条：下一次就能见面。裂缝会移动。别跟丢。——Kimo熊）下一次就能见面？',
        choices: [{ id: 'c', text: '（和小室对视了一眼）', nextNodeId: 's8' }],
        backgroundStyle: 'MANGA' },
      's8': { id: 's8', speakerName: '室友姐',
        text: '说明现在这些熊猫只是它留下的锚点。真正的 Kimo 熊——也许就在最后一个存档点。世界尽头的那个。',
        choices: [{ id: 'c', text: '如果下一条缝也不是回家的路呢？', nextNodeId: 's9' }] },
      's9': { id: 's9', speakerName: '室友姐',
        text: '那就继续走。',
        choices: [{ id: 'c', text: '你说得好轻松。', nextNodeId: 's10' }] },
      's10': { id: 's10', speakerName: '室友姐',
        text: '不轻松。只是你在旁边的话，就没那么难。',
        choices: [
          { id: 'a', text: '这种时候突然说这种话也太狡猾了。', nextNodeId: 'ra' },
          { id: 'b', text: '那我也会一直在你旁边。', affectionDelta: { charId: 'novus', amount: 15 }, nextNodeId: 'rb' },
          { id: 'cS', text: '【直球】如果出口每次都会换地方，那我的方向就只剩你了。', affectionDelta: { charId: 'novus', amount: 50 }, nextNodeId: 'rc', requiresClear: true },
        ] },
      'ra': { id: 'ra', speakerName: '室友姐',
        text: '狡猾的是这个世界。我只是实话实说。',
        choices: [{ id: 'c', text: '（把脸埋进外套里掩饰表情）', nextNodeId: 'end' }] },
      'rb': { id: 'rb', speakerName: '室友姐',
        text: '（把外套披在你肩上）嗯。那就互相看好对方，别跟丢。',
        choices: [{ id: 'c', text: '（外套上全是她的温度。）', nextNodeId: 'end' }] },
      'rc': { id: 'rc', speakerName: '室友姐',
        text: '（很久没有说话。云从脚下飘过去。然后她伸出手，把你的手攥进掌心）……那这个方向，以后不会再换地方了。',
        choices: [{ id: 'c', text: '（用力点头。）', nextNodeId: 'end' }] },
      'end': { id: 'end', speakerName: '李豆沙',
        text: '（第四张纸条。下一次，就能见到一直守着我存档的那个家伙了。）',
        choices: [{ id: 'c', text: '……', nextNodeId: null }] },
    },
  },

  // ---------- 第5关后：Kimo熊现身 · 最后的跳跃 · 普通结局 ----------
  'event3d_level5': {
    id: 'event3d_level5',
    requiredPageId: 'page3d_ch5',
    startNodeId: 's1',
    nodes: {
      's1': { id: 's1', speakerName: '李豆沙',
        text: '（世界接缝前。裂缝像一道呼吸的光。旁边——又蹲着一个熊猫存档点）……又是熊猫存档点。',
        choices: [{ id: 'c', text: '（习惯性地走过去想摸摸头）', nextNodeId: 's2' }] },
      's2': { id: 's2', speakerName: 'Kimo熊',
        text: '（熊猫轻轻亮了起来）终于到了。',
        choices: [{ id: 'c', text: '……你会说话？！', nextNodeId: 's3' }] },
      's3': { id: 's3', speakerName: '室友姐',
        text: '看来这不是普通存档点。',
        choices: [{ id: 'c', text: 'Kimo 熊？', nextNodeId: 's4' }] },
      's4': { id: 's4', speakerName: 'Kimo熊',
        text: '嗯。',
        choices: [{ id: 'c', text: '原来每个存档点都是你？', nextNodeId: 's5' }] },
      's5': { id: 's5', speakerName: 'Kimo熊',
        text: '不是全部。那些是我留下的锚点。这里，才是我。',
        choices: [{ id: 'c', text: '（小室：每次她掉下去，也是你把她送回来的？）', nextNodeId: 's6' }] },
      's6': { id: 's6', speakerName: 'Kimo熊',
        text: '嗯。',
        choices: [{ id: 'c', text: '那你为什么不早点出来！', nextNodeId: 's7' }] },
      's7': { id: 's7', speakerName: 'Kimo熊',
        text: '因为我不能离开锚点太远。我在等你们，走到最后一个存档点。——这里。',
        choices: [{ id: 'c', text: '（Kimo熊看向裂缝）', nextNodeId: 's8' }] },
      's8': { id: 's8', speakerName: 'Kimo熊',
        text: '过了这里，就超出我锚点的写入范围了。你们的坐标，我再也读取不到——跳进去以后，没有回档，没有读取，也可能，不会落在任何地方。',
        choices: [{ id: 'c', text: '（小室：所以这是不能重来的跳跃。）', nextNodeId: 's9' }],
        backgroundStyle: 'MANGA' },
      's9': { id: 's9', speakerName: 'Kimo熊',
        text: '嗯。',
        choices: [{ id: 'c', text: '那你还让我们跳？', nextNodeId: 's10' }] },
      's10': { id: 's10', speakerName: 'Kimo熊',
        text: '因为留在这里，你们会永远回到存档点。永远安全。也永远出不去。',
        choices: [{ id: 'c', text: '（沉默。裂缝的光在两个人脸上明明灭灭。）', nextNodeId: 's11' }],
        backgroundStyle: 'MANGA' },
      's11': { id: 's11', speakerName: '室友姐',
        text: '豆沙。这次如果掉下去，没有人能再把你回档了。',
        choices: [{ id: 'c', text: '那你来当我的存档点。', nextNodeId: 's12' }] },
      's12': { id: 's12', speakerName: '室友姐',
        text: '好。',
        choices: [
          { id: 'a', text: '走！这次也把它通关！', nextNodeId: 'jump' },
          { id: 'b', text: '牵紧我。不要又被世界分开。', affectionDelta: { charId: 'novus', amount: 15 }, nextNodeId: 'jump' },
          { id: 'cS', text: '【直球】我不确定哪里是家。但现在，我想把有你的地方先当成方向。', affectionDelta: { charId: 'novus', amount: 50 }, nextNodeId: 'jumpS', requiresClear: true },
        ] },
      'jump': { id: 'jump', speakerName: '李豆沙',
        text: '（回头朝 Kimo熊 用力挥了挥手，然后两个人牵着手，一起跳进了裂缝的光里。）',
        choices: [{ id: 'c', text: '……', nextNodeId: 'e1' }] },
      'jumpS': { id: 'jumpS', speakerName: '室友姐',
        text: '（她安静地看了你几秒，然后十指相扣，扣得很紧。）……那就跳吧。方向由你定，手由我牵。',
        choices: [{ id: 'c', text: '（两个人一起跳进了裂缝的光里。）', nextNodeId: 'e1' }] },
      // ---- 普通结局 ----
      'e1': { id: 'e1', speakerName: '旁白',
        text: '她们离开了最后一个 Kimo熊 存档点。也离开了那个永远会把她们接回来的安全位置。',
        choices: [{ id: 'c', text: '……', nextNodeId: 'e2' }],
        backgroundStyle: 'MANGA' },
      'e2': { id: 'e2', speakerName: '旁白',
        text: '裂缝的另一边，不一定是现实。但至少，那是没有被这个世界记录过的地方。',
        choices: [{ id: 'c', text: '……', nextNodeId: 'e3' }],
        backgroundStyle: 'MANGA' },
      'e3': { id: 'e3', speakerName: '李豆沙',
        text: '小室……这次如果掉下去，真的没有存档点了。',
        choices: [{ id: 'c', text: '……', nextNodeId: 'e4' }] },
      'e4': { id: 'e4', speakerName: '室友姐',
        text: '嗯。',
        choices: [{ id: 'c', text: '你害怕吗？', nextNodeId: 'e5' }] },
      'e5': { id: 'e5', speakerName: '室友姐',
        text: '有一点。',
        choices: [{ id: 'c', text: '那你刚才还说得那么帅。', nextNodeId: 'e6' }] },
      'e6': { id: 'e6', speakerName: '室友姐',
        text: '因为你比我更怕。',
        choices: [{ id: 'c', text: '……小室。', nextNodeId: 'e7' }] },
      'e7': { id: 'e7', speakerName: '室友姐',
        text: '嗯？',
        choices: [{ id: 'c', text: '牵紧点。', nextNodeId: 'e8' }] },
      'e8': { id: 'e8', speakerName: '室友姐',
        text: '早就牵紧了。',
        choices: [{ id: 'c', text: '（黑屏。）', nextNodeId: null }] },
    },
  },
};
